import "./globals.css";
import Bootstrap from "@/components/Bootstrap";
import Aos from "@/components/Aos";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

export const metadata = {
  title: "MarketPlace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Bootstrap/>
        <Aos/>
      </body>
    </html>
  );
}
